dont install debian recommends packages
rockandska/ansible-role-erlang pull request #7
Opened 2021-09-20 10:38 UTC by pad92

2021-09-20 11:36 UTC, rockandska commented
Thanks @pad92 

Does it solve #4 or not related ?

Regards,

2021-10-15 14:09 UTC, DisasteR commented
@rockandska yes it solve #4

2021-11-17 13:41 UTC, DisasteR commented
@rockandska any news about that one ?

2021-11-17 17:16 UTC, rockandska commented
> @rockandska any news about that one ?

Asked changed who was never addressed by @pad92

2021-11-18 08:50 UTC, DisasteR commented
> Asked changed who was never addressed by @pad92

what ?

2021-11-18 09:00 UTC, rockandska commented
> > Asked changed who was never addressed by @pad92
> 
> what ?

![image](https://user-images.githubusercontent.com/24546770/142383985-3cd427ea-66db-43f0-810b-886f4ba0db74.png)

2021-11-18 09:03 UTC, rockandska requested changes

2021-11-18 09:03 UTC, rockandska commented on tasks/install_Debian.yml
> +    install_recommends: no
could you please rebase with master and/or fix linting error by changing to `false` 
thanks

2021-11-18 09:03 UTC, rockandska commented on tasks/install_Debian.yml
> +    install_recommends: no
if you don't have the time to do it, let me access the [branch concerned by this PR](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) and I will do it.

2021-11-18 09:03 UTC, rockandska commented on tasks/install_Debian.yml
> +    install_recommends: no
Waiting for this to merge

2021-11-18 16:40 UTC, DisasteR commented on tasks/install_Debian.yml
> +    install_recommends: no
done

2021-11-18 17:26 UTC, rockandska approved these changes

2021-11-18 17:27 UTC, merged